# This is a basic workflow to help you get started with Actions

name: Maven Spring Boot CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Check branch
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Step 3 - Build Maven Project
        run: mvn -B package --file pom.xml
        
      - name: Step 4 - List the current directory
        run: ls -al
        
      - name: Step 5 - Target folder
        run: |
          cd target
          ls -a
